# Generated by Django 5.0.6 on 2026-05-13 02:01

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('username', models.CharField(db_index=True, help_text='Unique username for login', max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email address used for authentication', max_length=255, unique=True)),
                ('password', models.CharField(help_text='Hashed password', max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], db_index=True, help_text='User role determines permissions', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', help_text='Account status (e.g., PENDING, VERIFIED, SUSPENDED)', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user account is active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site')),
                ('auths', models.JSONField(default=list)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('access_code', models.CharField(editable=False, help_text='Auto-generated unique access code for parent-child linking', max_length=6, unique=True)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], help_text='Relationship between parent and student', max_length=20)),
                ('parent', models.ForeignKey(help_text='Parent user who requests the link', limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student user being linked', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_parents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent-Student Link',
                'verbose_name_plural': 'Parent-Student Links',
                'db_table': 'parents_students_links',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('roll_number', models.CharField(db_index=True, help_text='Student roll number', max_length=20)),
                ('class_level', models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10')], db_index=True, help_text='Current class level (6-10)')),
                ('section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], help_text='Section (A/B/C)', max_length=1)),
                ('group', models.CharField(blank=True, choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Business', 'Business Studies')], help_text='Group (required for Class 9-10, null for 6-8)', max_length=20, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('address', models.TextField(blank=True, help_text="Student's permanent address", null=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'students_profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identification number', max_length=50, unique=True)),
                ('department', models.CharField(choices=[('Science', 'Science Department'), ('Humanities', 'Humanities Department'), ('Business', 'Business Studies Department'), ('General', 'General Department')], help_text='Department the teacher belongs to', max_length=50)),
                ('designation', models.CharField(help_text='Job designation (e.g., Senior Teacher, Assistant Teacher)', max_length=100)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teachers_profiles',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('type', models.CharField(choices=[('ACCOUNT_VERIFICATION', 'Account Verification'), ('FORGOT_PASSWORD', 'Forgot password'), ('LOGIN_OTP_VERIFICATION', 'Login OTP Verification'), ('RESET_PASSWORD_OTP_VERIFICATION', 'Reset Password OTP Verification')], default='ACCOUNT_VERIFICATION', max_length=40)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_expiry)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'role'], name='users_email_7645ab_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'role'], name='users_usernam_adcd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='users_is_acti_930397_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentlink',
            index=models.Index(fields=['parent'], name='parents_stu_parent__f293f6_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentlink',
            index=models.Index(fields=['student'], name='parents_stu_student_4e822c_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentlink',
            index=models.Index(fields=['access_code'], name='parents_stu_access__317a58_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentlink',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student_link'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['class_level', 'section'], name='students_pr_class_l_0a1760_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['roll_number', 'class_level'], name='students_pr_roll_nu_f7cbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['group'], name='students_pr_group_f28f30_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('roll_number', 'class_level', 'section'), name='unique_roll_per_class_section'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['department'], name='teachers_pr_departm_9a8d63_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['employee_id'], name='teachers_pr_employe_a1a945_idx'),
        ),
    ]
