# Generated by Django 5.0.6 on 2026-05-13 02:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text="Exam name (e.g., 'Half-Yearly 2025')", max_length=200)),
                ('exam_type', models.CharField(choices=[('class_test', 'Class Test'), ('half_yearly', 'Half Yearly Exam'), ('annual', 'Annual/Final Exam')], db_index=True, help_text='Type of examination', max_length=20)),
                ('class_level', models.IntegerField(db_index=True, help_text='Class level for which this exam is conducted')),
                ('date', models.DateField(help_text='Exam date or start date')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether results have been published')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['exam_type', 'class_level'], name='exams_exam_ty_aa5c16_idx'), models.Index(fields=['is_published'], name='exams_is_publ_8bb3b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Full name of the subject (e.g., Bangla, English, Mathematics)', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Unique subject code (e.g., BAN101, ENG101)', max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('compulsory', 'Compulsory Subject'), ('optional_4th', 'Optional 4th Subject')], db_index=True, default='compulsory', help_text='Whether this is compulsory or optional 4th subject', max_length=20)),
                ('group', models.CharField(choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Business', 'Business Studies'), ('All', 'All Groups')], default='All', help_text='Subject group (Science/Humanities/Business/All)', max_length=20)),
                ('class_levels', models.JSONField(default=list, help_text='List of class levels this subject applies to (e.g., [6,7,8] or [9,10])')),
                ('has_practical', models.BooleanField(default=False, help_text='Does this subject have a practical component?')),
                ('full_marks', models.PositiveSmallIntegerField(default=100, help_text='Total full marks for this subject', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)])),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['subject_type'], name='subjects_subject_ce3821_idx'), models.Index(fields=['group'], name='subjects_group_dff818_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('section', models.CharField(help_text="Section identifier (e.g., '9A', '7B')", max_length=10)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2025-2026')", max_length=9)),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='subjectassignment_subject', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Assignment',
                'verbose_name_plural': 'Subject Assignments',
                'db_table': 'subjects_assignments',
            },
        ),
    ]
