# Generated by Django 5.0.6 on 2026-05-13 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher assigned to teach this subject', on_delete=django.db.models.deletion.CASCADE, related_name='subjectassignment_teacher', to='accounts.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['section', 'academic_year'], name='subjects_as_section_938550_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['teacher', 'academic_year'], name='subjects_as_teacher_7405c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'section', 'academic_year'), name='unique_teacher_subject_section_year'),
        ),
    ]
