# Generated by Django 5.0.6 on 2026-05-13 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(db_index=True, help_text='Date of attendance')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], db_index=True, help_text='Attendance status for the day', max_length=10)),
                ('section', models.CharField(db_index=True, help_text="Section identifier (e.g., '7B', '9A')", max_length=10)),
                ('marked_by', models.ForeignKey(help_text='Teacher who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked_by', to='accounts.teacherprofile')),
                ('student', models.ForeignKey(help_text='Student whose attendance is recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendances',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'section'], name='attendances_date_401b78_idx'), models.Index(fields=['student', 'date'], name='attendances_student_1e9785_idx'), models.Index(fields=['section', 'date'], name='attendances_section_5b9764_idx'), models.Index(fields=['status'], name='attendances_status_dae783_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_day'),
        ),
    ]
