# Generated by Django 5.0.6 on 2026-05-13 02:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('gpa', models.DecimalField(decimal_places=1, help_text='Calculated GPA on 5.0 scale', max_digits=3)),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Sum of all subject marks', max_digits=7)),
                ('total_grade_points', models.DecimalField(decimal_places=1, help_text='Sum of grade points from all subjects', max_digits=5)),
                ('number_of_subjects', models.PositiveSmallIntegerField(help_text='Number of subjects considered')),
                ('class_position', models.PositiveIntegerField(blank=True, help_text='Class position/rank', null=True)),
                ('is_passed', models.BooleanField(default=True, help_text='Did the student pass all compulsory subjects?')),
                ('exam', models.ForeignKey(help_text='Exam for which result is calculated', on_delete=django.db.models.deletion.CASCADE, related_name='studentresult_exam', to='academics.exam')),
                ('student', models.ForeignKey(help_text='Student for whom result is calculated', on_delete=django.db.models.deletion.CASCADE, related_name='studentresult_student', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': 'Student Results',
                'db_table': 'students_results',
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('marks_written', models.DecimalField(decimal_places=2, help_text='Marks obtained in written exam (0-75)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(75)])),
                ('marks_mcq', models.DecimalField(decimal_places=2, help_text='Marks obtained in MCQ exam (0-25)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('marks_practical', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained in practical exam (0-25), null for non-practical subjects', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('is_absent', models.BooleanField(default=False, help_text='Was the student absent for this exam?')),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated total marks (written + MCQ + practical)', max_digits=6, null=True)),
                ('letter_grade', models.CharField(blank=True, help_text='Auto-calculated letter grade (A+, A, A-, B, C, D, F)', max_length=3, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=1, help_text='Auto-calculated grade point (5.0, 4.0, 3.5, 3.0, 2.0, 1.0, 0.0)', max_digits=3, null=True)),
                ('exam', models.ForeignKey(help_text='Exam for which marks are entered', on_delete=django.db.models.deletion.CASCADE, related_name='studentmark_exam', to='academics.exam')),
                ('student', models.ForeignKey(help_text='Student receiving these marks', on_delete=django.db.models.deletion.CASCADE, related_name='studentmark_student', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(help_text='Subject for which marks are entered', on_delete=django.db.models.deletion.CASCADE, related_name='studentmark_subject', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'db_table': 'students_marks',
                'indexes': [models.Index(fields=['exam', 'subject'], name='students_ma_exam_id_ea5dce_idx'), models.Index(fields=['student', 'exam'], name='students_ma_student_f826af_idx'), models.Index(fields=['letter_grade'], name='students_ma_letter__84b6ba_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentmark',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'subject'), name='unique_student_exam_subject'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['exam', 'gpa'], name='students_re_exam_id_b3ab11_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['exam', 'class_position'], name='students_re_exam_id_4ed2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['student', 'exam'], name='students_re_student_4a3d8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentresult',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='unique_student_exam_result'),
        ),
    ]
